### ISSUE TITLE
Right-click harvesting not working

### ISSUE THREAD

**Issue by Dimentive** [KnightMiner/AnimalCrops#3]
Harvesting crops added by Animal Crops by right-clicking replants them but does not spawn the mobs. I have Pam’s HarvestCraft installed, which adds right-click harvesting; however, Animal Crops also adds its own right-click harvesting. Either Animal Crops’ right-click harvest feature isn’t working, or Pam’s HarvestCraft’s right-click harvesting feature, which presumably doesn’t work with Animal Crops, is overriding that of Animal Crops. There’s no right-click harvest blacklist or whitelist in Pam’s HarvestCraft config.

If Pam’s HarvestCraft _is_ overriding Animal Crops’ right-click harvest feature, perhaps Animal Crops should be updated to override other mods’ right-click harvesting to prevent issues like this from occurring? I don’t see why Animal Crops _wouldn’t_ be overriding other mods’ right-click harvest feature, though, considering the entire reason this feature exists in Animal Crops is that other mods’ right-click harvesting features don’t work with Animal Crops’ crops, but I don’t know.

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2816
* **Animal Crops:** 0.2.0 (latest)

**Comment by KnightMiner** [comment]
Animal Crops runs its right click harvest code where it should be, in the block right click method. Most other mods override block right click to add the harvest logic. I could use the same method, but it would be pretty hacky.

I would suggest requesting a blacklist from Pam's, that is the best solution.

**Comment by WenXin20** [comment]
The same problem seems to happen with the Repurpose mod right-click harvesting.

**Comment by KnightMiner** [comment]
I have this fixed in 1.14, unfortunately the fix I used is not possible in 1.12. As I mentioned before, the best solution is a blacklist as my right click harvest properly handles this.

Going to close this as the 1.12 version probably won't get any more releases.
