### ISSUE TITLE
When i broke the seed, the animals don't spawn. 

### ISSUE THREAD

**Issue by HurtsAsHell** [KnightMiner/AnimalCrops#4]
Hi, i'm creating a skyblock modpack, i can publish the list of mod if is needed.

There isn't a crash log because the game don't crash, i place the seed on the grass, use bone meal on it and broke it when is fully grow. The mob desn't spawn.

I haven't changed the config and all seeds are of vanilla mobs.

Do you know if is there a mod that remove the naturally spawn of mob?

Is a bug of mod or a mod incompatibility?

Do you need the latest log?

**Comment by HurtsAsHell** [comment]
I have tried to summon an entity but nothing, i recive "Unable to summon object". Could you help me?

**Comment by KnightMiner** [comment]
If summoning does not work, sounds like another mod is conflicting.

Do spawn eggs work fine? My crops use basically the same code as them.

**Comment by HurtsAsHell** [comment]
The egg are ok but not the seed and the summon command :(

**Comment by KnightMiner** [comment]
Are you on a server? If so, what type (sponge forge, normal forge, etc).

Also, what mods are you using? Can you reproduce this with just Animal Crops?

**Comment by HurtsAsHell** [comment]
Okay, i have solved, the problem was created by anorther mod

**Comment by KnightMiner** [comment]
Which other mod? Just in case someone else has this issue in the future
