### ISSUE TITLE
1.15 crash on launch

### ISSUE THREAD

**Issue by InfinitysDaughter** [KnightMiner/AnimalCrops#6]
(Hope I'm doing this right...)
I'm not sure if I'm missing a required library or something. I've tried pulling all mods out and adding them one at a time and AnimalCrops is the only one that keeps coming back with this crash.

[crash-2020-03-14_18.16.35-client.txt](https://github.com/KnightMiner/AnimalCrops/files/4333522/crash-2020-03-14_18.16.35-client.txt)

**Comment by KnightMiner** [comment]
That crash is from Doggy Talents, however I recognize this specific error as one that produces useless errors in the crash report. Can you link me your full game log, as that has the useful information?

**Comment by InfinitysDaughter** [comment]
*facepalm* Well now I feel really stupid. Removing DT fixed it. It must have slipped through the testing. >.< Apologies for my stupidness. ^^;

**Comment by InfinitysDaughter** [comment]
Oookkk. I take that back... (more of my stupid)

Here is the new crash and that other log.

[crash-2020-03-14_19.54.24-client.txt](https://github.com/KnightMiner/AnimalCrops/files/4333663/crash-2020-03-14_19.54.24-client.txt)
[latest.log](https://github.com/KnightMiner/AnimalCrops/files/4333664/latest.log)

**Comment by KnightMiner** [comment]
Yeah, as you can see from the crash report, its the same error, but from a different mod, pretty annoy Forge bug with this type of error.

The latest.log gave me the information I needed, looks like this is due to the 1.15.2 updates. Apparently Forge made a few breaking changes, and I have not had a chance to update for them yet. I will probably get to it early next week.

**Comment by InfinitysDaughter** [comment]
I'm glad I could help you find the problem. ^^ Cant wait for the fix but I can be patient so do as you do. c:

**Comment by KnightMiner** [comment]
Fixed in 0.5.0
