### ISSUE TITLE
Crash on 1.15.2

### ISSUE THREAD

**Issue by Kisonu** [KnightMiner/AnimalCrops#7]
Only thing i'm seeing is animal crops..  Full crash log is below.. Any hel would be much appreciated as i loved this mod in 1.12. 

Crash log
https://paste.ee/p/iTHQi

Im using multiMC launcher and a ton of mods but the crash happens on regular minecraft launcher too.

**Comment by KnightMiner** [comment]
That crash is caused by another mod erroring during startup, but Forge is dumb and continues trying to run mods after it crashed. Post your latest.log and I can figure out the actual mod causing problems.

**Comment by KnightMiner** [comment]
Closing for lack of response, as I said before, this is not an Animal Crops issue, but another mod. See also MinecraftForge/MinecraftForge#6374
