### ISSUE TITLE
Add entity by default (1.16)

### ISSUE THREAD

**Issue by North-West-Wind** [KnightMiner/AnimalCrops#8]
I realized you can only add mobs for crops in the server config file. Is there a way to set the default value outside of the world (i.e. Global config)?

**Comment by KnightMiner** [comment]
Default configs. Its a forge feature. I suggest asking on the Minecraft Forums or one of the discords for help setting them up, its a fairly common mod config feature

**Comment by North-West-Wind** [comment]
Alright I found it, thank you!
